"""Benchmark fingerprinting: discover language(s), source roots, frameworks.

This is the first stage of the systematic analysis pass. It runs **before**
any CodeQL is invoked: pure filesystem inspection, fast, no Docker, no DB
build. Its output drives everything else — taxonomy entries that don't apply
to a fingerprint are skipped (recorded in `coverage` so the analyzer can
distinguish "absent" from "untested"), and templates use the fingerprint's
package filters as their per-benchmark placeholders.

The detection rules below are intentionally conservative: where a heuristic
might be wrong, prefer reporting nothing over reporting a wrong thing —
the agent's prompt explicitly tells it to flag low-confidence fingerprints.
"""

from __future__ import annotations

import json
import re
from collections import Counter
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Iterable

# Skip these directories during the scan — they're either build output or
# vendored libraries that would distort the language vote.
_SKIP_DIRS = {
    ".git", ".svn", ".hg",
    "node_modules", "venv", ".venv", "env", ".env",
    "build", "dist", "out", "bin", "obj",
    "target",  # Maven
    ".mvn", ".gradle",
    "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache",
    "codeql-db", "codeql-queries",  # Generated by this very framework
    ".idea", ".vscode",
    "third_party", "third-party", "vendor", "deps",
}

# Build / framework signature files
_BUILD_FILES: dict[str, list[str]] = {
    "maven": ["pom.xml"],
    "gradle": ["build.gradle", "build.gradle.kts", "settings.gradle"],
    "cmake": ["CMakeLists.txt"],
    "make": ["Makefile", "makefile"],
    "pip": ["requirements.txt", "setup.py", "pyproject.toml"],
    "poetry": ["poetry.lock"],
    "go": ["go.mod"],
    "cargo": ["Cargo.toml"],
}

# Heuristic framework markers: regex matched against the *body* of selected files.
_FRAMEWORK_MARKERS: dict[str, list[tuple[str, str]]] = {
    "java": [
        ("spring", r"\borg\.springframework\."),
        ("springboot", r"\bspring-boot\b|@SpringBootApplication"),
        ("javax-servlet", r"\bjavax\.servlet\."),
        ("jakarta-servlet", r"\bjakarta\.servlet\."),
        ("jaxrs", r"@Path\b|\bjavax\.ws\.rs\."),
        ("hibernate", r"\borg\.hibernate\."),
        ("jpa", r"\bjavax\.persistence\.|\bjakarta\.persistence\."),
        ("jdbc", r"\bjava\.sql\.Connection\b"),
        ("netty", r"\bio\.netty\."),
        ("okhttp", r"\bokhttp3\."),
        ("apache-httpclient", r"\borg\.apache\.http\."),
        ("jackson", r"\bcom\.fasterxml\.jackson\."),
        ("gson", r"\bcom\.google\.gson\."),
        ("log4j", r"\borg\.apache\.log(4j|ging)\."),
    ],
    "cpp": [
        ("thrift", r"#include\s+[<\"]thrift/"),
        ("grpc", r"#include\s+[<\"]grpc/|grpcpp/"),
        ("boost", r"#include\s+[<\"]boost/"),
        ("std-thread", r"#include\s+[<\"]thread[>\"]"),
        ("std-mutex", r"#include\s+[<\"]mutex[>\"]"),
        ("openssl", r"#include\s+[<\"]openssl/"),
        ("mongocxx", r"#include\s+[<\"]mongocxx/"),
        ("redis-cpp", r"#include\s+[<\"]hiredis/|cpp_redis/"),
    ],
    "python": [
        ("flask", r"^from flask\b|^import flask\b"),
        ("fastapi", r"^from fastapi\b|^import fastapi\b"),
        ("django", r"^from django\b|^import django\b"),
        ("aiohttp", r"^from aiohttp\b|^import aiohttp\b"),
        ("requests", r"^import requests\b|^from requests\b"),
        ("sqlalchemy", r"^from sqlalchemy\b|^import sqlalchemy\b"),
        ("asyncio", r"^import asyncio\b|^from asyncio\b"),
    ],
}

# CodeQL-language identifier per detected source language
_CODEQL_LANG: dict[str, str] = {
    "java": "java",
    "cpp": "cpp",
    "python": "python",
}

# Source extensions per language
_LANG_EXTS: dict[str, set[str]] = {
    "java": {".java"},
    "cpp": {".cc", ".cpp", ".cxx", ".c", ".h", ".hh", ".hpp"},
    "python": {".py"},
}


@dataclass
class BenchmarkFingerprint:
    """Structured snapshot of a benchmark repository.

    The `package_filters` field is the most important downstream — every
    template uses it as the per-benchmark placeholder so generic queries
    don't drown in stdlib/vendored noise.
    """

    repo_path: str
    languages: list[str] = field(default_factory=list)
    primary_language: str = ""
    file_counts: dict[str, int] = field(default_factory=dict)
    line_counts: dict[str, int] = field(default_factory=dict)
    source_roots: dict[str, list[str]] = field(default_factory=dict)
    package_filters: dict[str, str] = field(default_factory=dict)
    frameworks: dict[str, list[str]] = field(default_factory=dict)
    build_systems: list[str] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return asdict(self)

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent, sort_keys=True)


def _iter_source_files(repo: Path, max_files: int = 8000) -> Iterable[tuple[Path, str]]:
    """Walk `repo` yielding (path, suffix) for source files.

    Generator + cap so a giant monorepo doesn't blow memory. The cap is
    conservative for the language-detection use case; we don't need every
    file — we just need the dominant signal.
    """
    seen = 0
    for path in repo.rglob("*"):
        if seen >= max_files:
            return
        # Skip excluded directories anywhere in the path
        parts = set(path.parts)
        if parts & _SKIP_DIRS:
            continue
        if not path.is_file():
            continue
        suffix = path.suffix.lower()
        if not suffix:
            continue
        for lang, exts in _LANG_EXTS.items():
            if suffix in exts:
                yield path, lang
                seen += 1
                break


def _detect_languages(repo: Path) -> tuple[dict[str, int], dict[str, int]]:
    """Return (file_counts, line_counts) per language."""
    file_counts: Counter = Counter()
    line_counts: Counter = Counter()
    for path, lang in _iter_source_files(repo):
        file_counts[lang] += 1
        try:
            # Cheap line count without loading whole file when very large
            with path.open("rb") as f:
                # Heuristic 200KB cap per file for the line count
                blob = f.read(200_000)
            line_counts[lang] += blob.count(b"\n")
        except Exception:
            continue
    return dict(file_counts), dict(line_counts)


def _detect_build_systems(repo: Path) -> list[str]:
    found: set[str] = set()
    for system, markers in _BUILD_FILES.items():
        for marker in markers:
            # Look for the marker file at any depth (not just root)
            for hit in repo.rglob(marker):
                if any(p in _SKIP_DIRS for p in hit.parts):
                    continue
                found.add(system)
                break
    return sorted(found)


def _java_top_package(repo: Path, sample_cap: int = 200) -> str:
    """Estimate the dominant top-level Java package by majority vote.

    Reads the `package` declaration from the first lines of up to `sample_cap`
    .java files and returns the longest common prefix at package-component
    granularity. Returns '' if no clear majority exists.
    """
    pkg_re = re.compile(r"^\s*package\s+([\w\.]+)\s*;", re.MULTILINE)
    sampled = 0
    pkgs: list[str] = []
    for path, lang in _iter_source_files(repo):
        if lang != "java":
            continue
        try:
            head = path.read_text(encoding="utf-8", errors="ignore")[:1024]
        except Exception:
            continue
        m = pkg_re.search(head)
        if m:
            pkgs.append(m.group(1))
            sampled += 1
            if sampled >= sample_cap:
                break
    if not pkgs:
        return ""
    # Find the longest package prefix (component-wise) shared by >= 70% of files
    threshold = max(2, int(0.7 * len(pkgs)))
    counter: Counter = Counter()
    for pkg in pkgs:
        components = pkg.split(".")
        for depth in range(1, len(components) + 1):
            counter[".".join(components[:depth])] += 1
    candidates = [
        (prefix, count) for prefix, count in counter.items() if count >= threshold
    ]
    if not candidates:
        return ""
    # Prefer the longest qualifying prefix
    candidates.sort(key=lambda x: (len(x[0]), x[1]), reverse=True)
    return candidates[0][0]


def _cpp_source_roots(repo: Path, sample_cap: int = 800) -> list[str]:
    """Estimate the source roots for a C++ repo.

    Heuristic: the top-3 directories (relative to repo root) with the most
    .cc/.cpp files, excluding tests. The most common DeathStarBench layout
    puts each service under `<benchmark>/src/<service>/...`, so we want
    the *parent* of that — typically `<benchmark>/src`.
    """
    counter: Counter = Counter()
    sampled = 0
    for path, lang in _iter_source_files(repo):
        if lang != "cpp":
            continue
        rel = path.relative_to(repo)
        # Take the first 3 components — that's typically enough to disambiguate
        parts = rel.parts[:-1]  # strip filename
        if any("test" in p.lower() for p in parts):
            continue
        for depth in range(1, min(3, len(parts)) + 1):
            counter["/".join(parts[:depth])] += 1
        sampled += 1
        if sampled >= sample_cap:
            break
    if not counter:
        return []
    # Take the top 3 distinct prefixes
    return [prefix for prefix, _ in counter.most_common(5)]


def _python_module_roots(repo: Path) -> list[str]:
    """Find Python module roots: directories containing __init__.py at top of a tree."""
    roots: list[str] = []
    for init_file in repo.rglob("__init__.py"):
        if any(p in _SKIP_DIRS for p in init_file.parts):
            continue
        rel_parent = init_file.parent.relative_to(repo)
        # Only collect "top-level" __init__.py: one whose parent has no __init__.py
        parent = init_file.parent.parent
        if parent != repo and (parent / "__init__.py").exists():
            continue
        roots.append(str(rel_parent))
    return sorted(set(roots))


def _detect_frameworks(
    repo: Path, languages: list[str], cap_per_lang: int = 80
) -> dict[str, list[str]]:
    """Scan a sample of files per language for framework markers."""
    out: dict[str, list[str]] = {lang: [] for lang in languages}
    seen_per_lang: dict[str, set[str]] = {lang: set() for lang in languages}
    sampled: dict[str, int] = {lang: 0 for lang in languages}
    for path, lang in _iter_source_files(repo):
        if lang not in languages:
            continue
        if sampled[lang] >= cap_per_lang:
            continue
        try:
            content = path.read_text(encoding="utf-8", errors="ignore")[:8000]
        except Exception:
            continue
        for fw, pattern in _FRAMEWORK_MARKERS.get(lang, []):
            if fw in seen_per_lang[lang]:
                continue
            if re.search(pattern, content, re.MULTILINE):
                seen_per_lang[lang].add(fw)
                out[lang].append(fw)
        sampled[lang] += 1
    return {lang: sorted(set(fws)) for lang, fws in out.items() if fws}


def fingerprint_repository(repo_path: str | Path) -> BenchmarkFingerprint:
    """Build a `BenchmarkFingerprint` for the given repo.

    Args:
        repo_path: Path to the repository root.

    Returns:
        Populated `BenchmarkFingerprint`. Always returns — even an unknown
        repo yields a valid fingerprint (with notes explaining what's
        missing). Callers should treat empty `languages` as a hard error
        upstream.
    """
    repo = Path(repo_path).resolve()
    notes: list[str] = []

    if not repo.exists() or not repo.is_dir():
        fp = BenchmarkFingerprint(repo_path=str(repo))
        fp.notes.append(f"Path does not exist or is not a directory: {repo}")
        return fp

    file_counts, line_counts = _detect_languages(repo)
    languages = sorted(file_counts.keys(), key=lambda l: -file_counts[l])
    primary = languages[0] if languages else ""

    package_filters: dict[str, str] = {}
    source_roots: dict[str, list[str]] = {}

    if "java" in languages:
        top_pkg = _java_top_package(repo)
        if top_pkg:
            package_filters["java"] = f"{top_pkg}.%"
            source_roots["java"] = [top_pkg]
        else:
            notes.append(
                "Java sources detected but no dominant package prefix found; "
                "queries will not filter by package and may include vendored code."
            )
            package_filters["java"] = "%"

    if "cpp" in languages:
        roots = _cpp_source_roots(repo)
        if roots:
            source_roots["cpp"] = roots
            # Use the most common root as the primary filter
            package_filters["cpp"] = roots[0]
        else:
            notes.append("C++ sources detected but no dominant source root.")
            package_filters["cpp"] = ""

    if "python" in languages:
        roots = _python_module_roots(repo)
        if roots:
            source_roots["python"] = roots
            package_filters["python"] = roots[0]
        else:
            notes.append("Python sources detected but no top-level package directory.")
            package_filters["python"] = ""

    frameworks = _detect_frameworks(repo, languages)
    build_systems = _detect_build_systems(repo)

    fp = BenchmarkFingerprint(
        repo_path=str(repo),
        languages=languages,
        primary_language=primary,
        file_counts=file_counts,
        line_counts=line_counts,
        source_roots=source_roots,
        package_filters=package_filters,
        frameworks=frameworks,
        build_systems=build_systems,
        notes=notes,
    )
    return fp
